[tox]
env_list = py312
requires = tox>=4

[testenv]
description = Run pytest with coverage for check_missing_files script
package = skip
deps =
    pytest
    coverage
set_env =
    PYTHONPATH = {toxinidir}
commands =
    coverage run -m pytest test_check_missing_files_between_two_folders.py
    coverage report
